const dailyData = [
    { jp: "元気ですか？", en: "How are you?", cn: "你好吗？| Nǐ hǎo ma?", kr: "잘 지냈어요? | チャル チネッソヨ？", es: "¿Cómo estás? | コモ エスタス？" },
    { jp: "いい天気ですね", en: "Nice weather, isn't it?", cn: "天气很好，对吧？| Tiānqì hěn hǎo, duì ba?", kr: "날씨 좋네요 | ナルシ チョンネヨ", es: "Hace buen tiempo, ¿verdad? | アセ ブエン ティエンポ ベルダ？" },
    { jp: "最近どう？", en: "How's it going?", cn: "最近怎么样？| Zuìjìn zěnmeyàng?", kr: "요즘 어때요? | ヨジュム オッテヨ？", es: "¿Cómo te va? | コモ テ バ？" },
    { jp: "久しぶりですね", en: "Long time no see", cn: "好久不见 | Hǎojiǔ bújiàn", kr: "오랜만이에요 | オレンマニエヨ", es: "Cuánto tiempo sin verte | クアント ティエンポ シン ベルテ" },
    { jp: "お名前は？", en: "What’s your name?", cn: "你叫什么名字？| Nǐ jiào shénme míngzì?", kr: "이름이 뭐예요? | イルミ モエヨ？", es: "¿Cómo te llamas? | コモ テ ジャマス？" },
    { jp: "どこに住んでいますか？", en: "Where do you live?", cn: "你住在哪里？| Nǐ zhù zài nǎlǐ?", kr: "어디에 살아요? | オディエ サラヨ？", es: "¿Dónde vives? | ドンデ ビベス？" },
    { jp: "趣味は何ですか？", en: "What’s your hobby?", cn: "你的爱好是什么？| Nǐ de àihào shì shénme?", kr: "취미가 뭐예요? | チュイミガ モエヨ？", es: "¿Cuál es tu pasatiempo? | クアル エス トゥ パサティエンポ？" },
    { jp: "コーヒーが好きです", en: "I like coffee", cn: "我喜欢咖啡 | Wǒ xǐhuān kāfēi", kr: "커피 좋아해요 | コピ チョアヘヨ", es: "Me gusta el café | メ グスタ エル カフェ" },
    { jp: "週末は何をしましたか？", en: "What did you do on the weekend?", cn: "周末你做了什么？| Zhōumò nǐ zuòle shénme?", kr: "주말에 뭐 했어요? | チュマレ モ ヘッソヨ？", es: "¿Qué hiciste el fin de semana? | ケ イシステ エル フィン デ セマナ？" },
    { jp: "それはいいですね！", en: "That sounds great!", cn: "那听起来不错！| Nà tīng qǐlái bùcuò!", kr: "좋네요! | チョンネヨ！", es: "¡Suena genial! | スエナ ヘニアル！" },
    { jp: "今日は忙しいです", en: "I'm busy today", cn: "我今天很忙 | Wǒ jīntiān hěn máng", kr: "오늘 바빠요 | オヌル パッパヨ", es: "Estoy ocupado hoy | エストイ オクパド オイ" },
    { jp: "映画を見ました", en: "I watched a movie", cn: "我看了一部电影 | Wǒ kànle yí bù diànyǐng", kr: "영화 봤어요 | ヨンファ バッソヨ", es: "Vi una película | ビ ウナ ペリクーラ" },
    { jp: "おめでとうございます", en: "Congratulations", cn: "恭喜 | Gōngxǐ", kr: "축하합니다 | チュッカハムニダ", es: "Felicidades | フェリシダデス" },
    { jp: "それは残念ですね", en: "That's too bad", cn: "那太遗憾了 | Nà tài yíhàn le", kr: "아쉽네요 | アシムネヨ", es: "Qué pena | ケ ペナ" },
    { jp: "手伝いましょうか？", en: "Shall I help you?", cn: "要我帮忙吗？| Yào wǒ bāngmáng ma?", kr: "도와드릴까요? | トワドゥリルカヨ？", es: "¿Te ayudo? | テ アユド？" },
    { jp: "大丈夫です", en: "I'm okay", cn: "没关系 | Méiguānxi", kr: "괜찮아요 | ケンチャナヨ", es: "Estoy bien | エストイ ビエン" },
    { jp: "いくつですか？", en: "How old are you?", cn: "你几岁？| Nǐ jǐ suì?", kr: "몇 살이에요? | ミョッサリエヨ？", es: "¿Cuántos años tienes? | クアントス アニョス ティエネス？" },
    { jp: "学生ですか？", en: "Are you a student?", cn: "你是学生吗？| Nǐ shì xuéshēng ma?", kr: "학생이에요? | ハクセンイエヨ？", es: "¿Eres estudiante? | エレス エストゥディアンテ？" },
    { jp: "仕事は何をしていますか？", en: "What do you do?", cn: "你做什么工作？| Nǐ zuò shénme gōngzuò?", kr: "무슨 일 해요? | ムスン イル ヘヨ？", es: "¿A qué te dedicas? | ア ケ テ デディカス？" },
    { jp: "日本に来たことがありますか？", en: "Have you been to Japan?", cn: "你去过日本吗？| Nǐ qùguò Rìběn ma?", kr: "일본에 가본 적 있어요? | イルボネ カボン ジョク イッソヨ？", es: "¿Has estado en Japón? | アス エスタド エン ハポン？" },
    { jp: "英語を勉強しています", en: "I'm studying English", cn: "我在学英语 | Wǒ zài xué Yīngyǔ", kr: "영어 공부하고 있어요 | ヨンオ コンブハゴ イッソヨ", es: "Estoy estudiando inglés | エストイ エストゥディアンド イングレス" },
    { jp: "毎日忙しいです", en: "I'm busy every day", cn: "我每天都很忙 | Wǒ měitiān dōu hěn máng", kr: "매일 바빠요 | メイル パッパヨ", es: "Estoy ocupado todos los días | エストイ オクパド トドス ロス ディアス" },
    { jp: "旅行が好きです", en: "I like traveling", cn: "我喜欢旅行 | Wǒ xǐhuān lǚxíng", kr: "여행 좋아해요 | ヨヘン チョアヘヨ", es: "Me gusta viajar | メ グスタ ビアハール" },
    { jp: "スポーツが好きです", en: "I like sports", cn: "我喜欢运动 | Wǒ xǐhuān yùndòng", kr: "운동 좋아해요 | ウンドン チョアヘヨ", es: "Me gustan los deportes | メ グスタン ロス デポルテス" },
    { jp: "今日は疲れました", en: "I'm tired today", cn: "我今天很累 | Wǒ jīntiān hěn lèi", kr: "오늘 피곤해요 | オヌル ピゴネヨ", es: "Estoy cansado hoy | エストイ カンサド オイ" },
    { jp: "いい一日を！", en: "Have a nice day!", cn: "祝你有美好的一天！| Zhù nǐ yǒu měihǎo de yītiān!", kr: "좋은 하루 되세요! | チョウン ハル ドゥセヨ！", es: "¡Que tengas un buen día! | ケ テンガス ウン ブエン ディア！" },
    { jp: "頑張って！", en: "Good luck!", cn: "加油！| Jiāyóu!", kr: "화이팅! | ファイティン！", es: "¡Buena suerte! | ブエナ スエルテ！" },
    { jp: "また会いましょう", en: "See you again", cn: "再见 | Zàijiàn", kr: "또 만나요 | ト マンナヨ", es: "Nos vemos | ノス ベモス" },
    { jp: "お疲れさまでした", en: "Good job", cn: "辛苦了 | Xīnkǔ le", kr: "수고하셨습니다 | スゴハショッスムニダ", es: "Buen trabajo | ブエン トラバホ" },
    { jp: "さようなら", en: "Goodbye", cn: "再见 | Zàijiàn", kr: "안녕히 가세요 | アンニョンヒ カセヨ", es: "Adiós | アディオス" }
  ];
  